---
- name: Copy the Elasticsearch Exporter systemd service file
  template:
    src: elasticsearch_exporter.service.j2
    dest: /etc/systemd/system/elasticsearch_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch_exporter

- name: Allow Elasticsearch Exporter in SELinux on Redhat OS family
  seport:
    ports: "{{ es_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
