---
- name: Gether variable for each operation system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - es_exporter_install
    - es_exporter_configure
    - es_exporter_run

- import_tasks: preflight.yml
  tags:
    - es_exporter_install
    - es_exporter_configure
    - es_exporter_run

- import_tasks: install.yml
  become: true
  when: (not __es_exporter_is_installed.stat.exists) or (__es_exporter_current_version_output.stderr_lines[0].split(" ")[2] != es_exporter_version)
  tags:
    - es_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - es_exporter_configure

- name: Ensure Elasticsearch Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: elasticsearch_exporter
    enabled: true
    state: started
  tags:
    - es_exporter_run
