---
- name: Assert usage of systemd as a init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  set_fact:
    es_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in es_exporter_web_listen_address"

- name: Check if elasticsearch_exporter is installed
  stat:
    path: "/usr/local/bin/elasticsearch_exporter"
  register: __es_exporter_is_installed
  check_mode: false
  tags:
    - es_exporter_install

- name: Gather currently installed elasticsearch_exporter version (if any)
  command: "/usr/local/bin/elasticsearch_exporter --version"
  args:
    warn: false
  changed_when: false
  register: __es_exporter_current_version_output
  check_mode: false
  when: __es_exporter_is_installed.stat.exists
  tags:
    - es_exporter_install

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/justwatchcom/elasticsearch_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release.status == 200
      retries: 5

    - name: "Set elasticsearch_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        es_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - es_exporter_version == "latest"
    - es_exporter_binary_local_dir | length == 0


- name: "Get checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
  set_fact:
    __es_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', 'https://github.com/justwatchcom/elasticsearch_exporter/releases/download/v' + es_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture)) + '.tar.gz') in item"
